/* eslint-disable */

const express = require('express');
const webpack = require('webpack');
const webpackDevMiddleware = require('webpack-dev-middleware');
const webpackHotMiddleware = require('webpack-hot-middleware');
const path = require('path');
const config = require('./webpack.config');
const constants = require('./config/constants');

const app = express();
const port = constants.port;

app.use(express.static('public'));

const compiler = webpack(config);
const devMiddleware = webpackDevMiddleware(compiler, {
  noInfo: true,
  publicPath: config.output.publicPath,
  index: 'index.html'
});
app.use(devMiddleware);
app.use(webpackHotMiddleware(compiler));

app.use(function(req, res, next) {
  // res.sendFile(__dirname + '/index.html');
  // Since index.html is dynamicly generated by html-webpack-plugin,
  // we cannot access it from the local file system.
  // just rewrite the request and call devMiddleware again
  req.url = '/index.html';
  devMiddleware(req, res, next);
});


app.listen(port, function success(error) {
  if (error) {
    console.error(error);
  } else {
    console.info('==> 🌎  Listening on port %s. Open up http://localhost:%s/ in your browser.', port, port);
  }
});
